name: Build and Deploy Back-End

on:
  push:
    branches:
      - master
      - backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - name: Prepare Files ðŸ”§
        run: |
          cd ./back-end/
          pip3 install pipenv
          python3 -m pipenv lock -r > requirements.txt
          zip deploy.zip *

      - name: Deploy ðŸš€
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: nuvola
          environment_name: Nuvola-env
          version_label: "nuvola-backend"
          version_description: ${{ github.SHA }}
          region: us-east-2
          deployment_package: deploy.zip
