name: Build and Deploy Back-End

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup PDM ğŸ”§
        uses: pdm-project/setup-pdm@v3

      - name: Export requirements.txt ğŸ”§
        run: |
          cd back-end
          make requirements.txt

      - name: Deploy ğŸš€
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'meldy'
          deta-project: 'bubblefishstudio'
          deta-project-dir: 'back-end'
