name: Build and Deploy Back-End

on:
  push:
    branches:
      - master
      - backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Prepare Files ğŸ”§
        run: |
          echo "nothing to do!"

      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          publish_dir: ./back-end/
          publish_branch: heroku
          github_token: ${{ secrets.GITHUB_TOKEN }}
